server:
  port: 9008
spring:
  application:
    name: tensquare-user #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 47.94.207.39
  redis:
    host: 47.94.207.39
jwt:
  config:
    key: itcast
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka   #指定Eureka注册地址